package handlers

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"regexp"
	"testing"
	"time"

	"github.com/gofiber/fiber/v2"
)

func TestOrbitCadenceHoursComplete(t *testing.T) {
	expected := map[string]float64{
		"daily":   24,
		"weekly":  168,
		"monthly": 720,
	}
	for cadence, hours := range expected {
		got, ok := orbitCadenceHours[cadence]
		if !ok {
			t.Errorf("missing cadence %q in orbitCadenceHours", cadence)
			continue
		}
		if got != hours {
			t.Errorf("orbitCadenceHours[%q] = %v, want %v", cadence, got, hours)
		}
	}
}

func TestIsDue(t *testing.T) {
	now := time.Now().UTC()

	tests := []struct {
		name      string
		cadence   string
		lastRunAt string
		wantDue   bool
	}{
		{
			name:      "daily mission run 25h ago is due",
			cadence:   "daily",
			lastRunAt: now.Add(-25 * time.Hour).Format(time.RFC3339),
			wantDue:   true,
		},
		{
			name:      "daily mission run 23h ago is not due",
			cadence:   "daily",
			lastRunAt: now.Add(-23 * time.Hour).Format(time.RFC3339),
			wantDue:   false,
		},
		{
			name:      "weekly mission run 8 days ago is due",
			cadence:   "weekly",
			lastRunAt: now.Add(-8 * 24 * time.Hour).Format(time.RFC3339),
			wantDue:   true,
		},
		{
			name:      "weekly mission run 6 days ago is not due",
			cadence:   "weekly",
			lastRunAt: now.Add(-6 * 24 * time.Hour).Format(time.RFC3339),
			wantDue:   false,
		},
		{
			name:      "monthly mission run 31 days ago is due",
			cadence:   "monthly",
			lastRunAt: now.Add(-31 * 24 * time.Hour).Format(time.RFC3339),
			wantDue:   true,
		},
		{
			name:      "never-run mission is due",
			cadence:   "weekly",
			lastRunAt: "",
			wantDue:   true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := &OrbitMission{
				Cadence: tt.cadence,
				AutoRun: true,
			}
			if tt.lastRunAt != "" {
				m.LastRunAt = &tt.lastRunAt
			}

			cadenceHrs, ok := orbitCadenceHours[m.Cadence]
			if !ok {
				t.Fatalf("unknown cadence %q", m.Cadence)
			}

			isDue := false
			if m.LastRunAt == nil || *m.LastRunAt == "" {
				isDue = true
			} else {
				lastRun, err := time.Parse(time.RFC3339, *m.LastRunAt)
				if err != nil {
					t.Fatalf("invalid lastRunAt: %v", err)
				}
				elapsed := time.Since(lastRun).Hours()
				isDue = elapsed >= cadenceHrs
			}

			if isDue != tt.wantDue {
				t.Errorf("isDue = %v, want %v", isDue, tt.wantDue)
			}
		})
	}
}

// TestCreateMission_AutoGeneratedID verifies that creating a mission without
// an explicit ID produces one with the expected shape:
//
// orbit-<14-digit-datetime>.<3-digit-ms>-<4-hex-suffix>
//
// This guards against regressions in generateOrbitSuffix (#7855 / #7815) — in
// particular it prevents the broken fallback `time.Now().Format("0000")` which
// would emit the literal string "0000" instead of random hex.
func TestCreateMission_AutoGeneratedID(t *testing.T) {
	// Write to a temp dir so we don't touch the real data directory.
	h := NewOrbitHandler(t.TempDir(), nil)
	app := fiber.New()
	app.Post("/missions", h.CreateMission)

	payload, err := json.Marshal(map[string]any{
		"title":     "Test Mission",
		"orbitType": "health-check",
		"cadence":   "daily",
	})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	req, err := http.NewRequest(http.MethodPost, "/missions", bytes.NewReader(payload))
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")

	// fiberTestTimeoutMS: test-local timeout (ms) for the in-process Fiber test.
	const fiberTestTimeoutMS = 5000
	resp, err := app.Test(req, fiberTestTimeoutMS)
	if err != nil {
		t.Fatalf("app.Test: %v", err)
	}
	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		t.Fatalf("status = %d, want 201; body=%s", resp.StatusCode, string(body))
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read body: %v", err)
	}
	var got OrbitMission
	if err := json.Unmarshal(body, &got); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	// Expected format: orbit-YYYYMMDDHHMMSS.mmm-xxxx (xxxx = hex)
	idPattern := regexp.MustCompile(`^orbit-\d{14}\.\d{3}-[0-9a-f]{4}$`)
	if !idPattern.MatchString(got.ID) {
		t.Errorf("ID = %q, want match %s", got.ID, idPattern)
	}

	// Sanity: the suffix must not be the literal "0000" fallback from the old
	// broken time.Format("0000") behavior. Given crypto/rand, collision with
	// "0000" is 1/65536 — acceptable for a single test invocation.
	if len(got.ID) >= 4 && got.ID[len(got.ID)-4:] == "0000" {
		t.Errorf("ID suffix is literal 0000, suggests broken random fallback: %q", got.ID)
	}
}

// TestGenerateOrbitSuffix_ShapeAndVariability verifies the suffix is always
// 4 lowercase hex characters and that successive calls produce different
// values (probabilistically — 1/65536 collision chance per call).
func TestGenerateOrbitSuffix_ShapeAndVariability(t *testing.T) {
	const suffixHexChars = 4
	pat := regexp.MustCompile(`^[0-9a-f]{4}$`)
	seen := make(map[string]struct{})
	// sampleSize: enough calls that total collision across all samples is
	// statistically negligible (1 - (1-1/65536)^N stays tiny for N=16).
	const sampleSize = 16
	for i := 0; i < sampleSize; i++ {
		s := generateOrbitSuffix()
		if len(s) != suffixHexChars {
			t.Errorf("suffix %q length = %d, want %d", s, len(s), suffixHexChars)
		}
		if !pat.MatchString(s) {
			t.Errorf("suffix %q does not match %s", s, pat)
		}
		seen[s] = struct{}{}
	}
	if len(seen) < 2 {
		t.Errorf("generateOrbitSuffix produced the same value %d times — not random", sampleSize)
	}
}

func TestOrbitMissionSerialization(t *testing.T) {
	m := &OrbitMission{
		ID:          "test-1",
		Title:       "Health Check",
		Description: "Check pod health",
		OrbitType:   "health-check",
		Cadence:     "weekly",
		AutoRun:     true,
		Clusters:    []string{"cluster-a"},
		Steps: []OrbitStep{
			{Title: "Check pods", Description: "Verify all pods running"},
		},
		CreatedAt: time.Now().UTC().Format(time.RFC3339),
		History:   []OrbitRunRecord{},
	}

	if m.ID != "test-1" {
		t.Errorf("ID = %q, want %q", m.ID, "test-1")
	}
	if m.OrbitType != "health-check" {
		t.Errorf("OrbitType = %q, want %q", m.OrbitType, "health-check")
	}
	if !m.AutoRun {
		t.Error("AutoRun should be true")
	}
	if len(m.Steps) != 1 {
		t.Errorf("Steps len = %d, want 1", len(m.Steps))
	}
	if m.LastRunAt != nil {
		t.Error("LastRunAt should be nil for new mission")
	}
}

type orbitTestExecutor struct {
	result      string
	summary     string
	err         error
	calls       int
	lastMission *OrbitMission
}

func (e *orbitTestExecutor) Execute(_ context.Context, mission *OrbitMission) (string, string, error) {
	e.calls++
	e.lastMission = mission
	return e.result, e.summary, e.err
}

type orbitRunResponse struct {
	MissionID string `json:"missionId"`
	RunAt     string `json:"runAt"`
	Result    string `json:"result"`
	Summary   string `json:"summary"`
}

func TestRunMissionReturnsSkippedWithoutExecutor(t *testing.T) {
	h := NewOrbitHandler(t.TempDir(), nil)
	h.missions["orbit-skip"] = &OrbitMission{
		ID:        "orbit-skip",
		Title:     "Health Check",
		OrbitType: "health-check",
		Cadence:   "daily",
		Steps: []OrbitStep{{
			Title:       "Check pod health",
			Description: "Verify all pods are healthy.",
		}},
		History: []OrbitRunRecord{},
	}

	app := fiber.New()
	app.Post("/missions/:id/run", h.RunMission)

	req, err := http.NewRequest(http.MethodPost, "/missions/orbit-skip/run", nil)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	const fiberTestTimeoutMS = 5000
	resp, err := app.Test(req, fiberTestTimeoutMS)
	if err != nil {
		t.Fatalf("app.Test: %v", err)
	}
	defer resp.Body.Close()

	var got orbitRunResponse
	if err := json.NewDecoder(resp.Body).Decode(&got); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if got.MissionID != "orbit-skip" {
		t.Fatalf("missionId = %q, want orbit-skip", got.MissionID)
	}
	if got.RunAt == "" {
		t.Fatal("runAt should be populated")
	}
	if got.Result != "skipped" {
		t.Fatalf("result = %q, want skipped", got.Result)
	}
	if got.Summary != orbitRunMissionNoExecutorSummary {
		t.Fatalf("summary = %q, want %q", got.Summary, orbitRunMissionNoExecutorSummary)
	}
	if h.missions["orbit-skip"].LastRunResult == nil || *h.missions["orbit-skip"].LastRunResult != "skipped" {
		t.Fatalf("LastRunResult = %v, want skipped", h.missions["orbit-skip"].LastRunResult)
	}
	if len(h.missions["orbit-skip"].History) != 1 || h.missions["orbit-skip"].History[0].Summary != orbitRunMissionNoExecutorSummary {
		t.Fatalf("history summary = %+v, want persisted skip summary", h.missions["orbit-skip"].History)
	}
}

func TestRunMissionUsesExecutorResult(t *testing.T) {
	executor := &orbitTestExecutor{result: "success", summary: "Mission executed against 2 clusters"}
	h := NewOrbitHandler(t.TempDir(), executor)
	h.missions["orbit-success"] = &OrbitMission{
		ID:        "orbit-success",
		Title:     "Health Check",
		OrbitType: "health-check",
		Cadence:   "daily",
		Clusters:  []string{"cluster-a", "cluster-b"},
		Steps: []OrbitStep{{
			Title:       "Check cluster health",
			Description: "Verify cluster health is good.",
		}},
		History: []OrbitRunRecord{},
	}

	app := fiber.New()
	app.Post("/missions/:id/run", h.RunMission)

	req, err := http.NewRequest(http.MethodPost, "/missions/orbit-success/run", nil)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	const fiberTestTimeoutMS = 5000
	resp, err := app.Test(req, fiberTestTimeoutMS)
	if err != nil {
		t.Fatalf("app.Test: %v", err)
	}
	defer resp.Body.Close()

	var got orbitRunResponse
	if err := json.NewDecoder(resp.Body).Decode(&got); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if got.Result != "success" {
		t.Fatalf("result = %q, want success", got.Result)
	}
	if got.Summary != executor.summary {
		t.Fatalf("summary = %q, want %q", got.Summary, executor.summary)
	}
	if executor.calls != 1 {
		t.Fatalf("executor calls = %d, want 1", executor.calls)
	}
	if executor.lastMission == nil || executor.lastMission.ID != "orbit-success" {
		t.Fatalf("executor mission = %+v, want orbit-success", executor.lastMission)
	}
	if len(h.missions["orbit-success"].History) != 1 || h.missions["orbit-success"].History[0].Summary != executor.summary {
		t.Fatalf("history = %+v, want stored success summary", h.missions["orbit-success"].History)
	}
}

func TestRunMissionMarksFailureWhenExecutorErrors(t *testing.T) {
	executorErr := errors.New("executor failed to contact clusters")
	executor := &orbitTestExecutor{err: executorErr}
	h := NewOrbitHandler(t.TempDir(), executor)
	h.missions["orbit-failure"] = &OrbitMission{
		ID:        "orbit-failure",
		Title:     "Health Check",
		OrbitType: "health-check",
		Cadence:   "daily",
		History:   []OrbitRunRecord{},
	}

	app := fiber.New()
	app.Post("/missions/:id/run", h.RunMission)

	req, err := http.NewRequest(http.MethodPost, "/missions/orbit-failure/run", nil)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	const fiberTestTimeoutMS = 5000
	resp, err := app.Test(req, fiberTestTimeoutMS)
	if err != nil {
		t.Fatalf("app.Test: %v", err)
	}
	defer resp.Body.Close()

	var got orbitRunResponse
	if err := json.NewDecoder(resp.Body).Decode(&got); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if got.Result != "failed" {
		t.Fatalf("result = %q, want failed", got.Result)
	}
	const wantSummary = "mission execution failed"
	if got.Summary != wantSummary {
		t.Fatalf("summary = %q, want %q", got.Summary, wantSummary)
	}
	if len(h.missions["orbit-failure"].History) != 1 || h.missions["orbit-failure"].History[0].Result != "failed" {
		t.Fatalf("history = %+v, want failed result", h.missions["orbit-failure"].History)
	}
}

func TestCheckDueMissionsRecordsSkippedWithoutExecutor(t *testing.T) {
	h := NewOrbitHandler(t.TempDir(), nil)
	h.missions["orbit-auto-skip"] = &OrbitMission{
		ID:        "orbit-auto-skip",
		Title:     "Health Check",
		OrbitType: "health-check",
		Cadence:   "daily",
		AutoRun:   true,
		History:   []OrbitRunRecord{},
	}

	h.checkDueMissions()

	mission := h.missions["orbit-auto-skip"]
	if mission.LastRunResult == nil || *mission.LastRunResult != "skipped" {
		t.Fatalf("LastRunResult = %v, want skipped", mission.LastRunResult)
	}
	if len(mission.History) != 1 {
		t.Fatalf("history len = %d, want 1", len(mission.History))
	}
	if mission.History[0].Summary != orbitSchedulerNoExecutorSummary {
		t.Fatalf("history summary = %q, want %q", mission.History[0].Summary, orbitSchedulerNoExecutorSummary)
	}
}

func TestCheckDueMissionsUsesExecutorResult(t *testing.T) {
	executor := &orbitTestExecutor{result: "completed", summary: "Scheduled mission ran successfully"}
	h := NewOrbitHandler(t.TempDir(), executor)
	h.missions["orbit-auto-success"] = &OrbitMission{
		ID:        "orbit-auto-success",
		Title:     "Health Check",
		OrbitType: "health-check",
		Cadence:   "daily",
		AutoRun:   true,
		History:   []OrbitRunRecord{},
	}

	h.checkDueMissions()

	mission := h.missions["orbit-auto-success"]
	if executor.calls != 1 {
		t.Fatalf("executor calls = %d, want 1", executor.calls)
	}
	if mission.LastRunResult == nil || *mission.LastRunResult != "completed" {
		t.Fatalf("LastRunResult = %v, want completed", mission.LastRunResult)
	}
	if len(mission.History) != 1 || mission.History[0].Summary != executor.summary {
		t.Fatalf("history = %+v, want stored executor summary", mission.History)
	}
}
