/**
 * Centralized icon registry using named imports from lucide-react.
 *
 * All Lucide icons used in the app are imported here by name, enabling bundler
 * tree-shaking to eliminate unused icons from the production bundle.
 *
 * When adding a new icon to the app, add it here first.
 */
import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Anchor,
  Apple,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpFromLine,
  ArrowUpRight,
  Award,
  Banana,
  BarChart2,
  BarChart3,
  Bell,
  BellOff,
  Bird,
  Bomb,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Calendar,
  CalendarDays,
  Car,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleDot,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudFog,
  CloudRain,
  CloudSnow,
  Club,
  Code,
  Code2,
  Cog,
  Coins,
  Columns,
  Compass,
  Container,
  Copy,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Diff,
  DollarSign,
  Download,
  Edit,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck,
  FileCode,
  FileDiff,
  FileJson,
  FileKey,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderGit,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Footprints,
  FormInput,
  Gamepad2,
  Gauge,
  Ghost,
  Gift,
  GitBranch,
  GitCompare,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  Grid2X2,
  Grid3X3,
  GripVertical,
  Hammer,
  HardDrive,
  Heart,
  HeartPulse,
  HelpCircle,
  Hexagon,
  History,
  Hourglass,
  Image,
  ImageOff,
  Info,
  Key,
  KeyRound,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Lightbulb,
  Link,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  MemoryStick,
  Menu,
  MessageSquare,
  MessageSquareText,
  Microscope,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Navigation,
  Network,
  Newspaper,
  Package,
  Palette,
  Pause,
  Pencil,
  Percent,
  PieChart,
  Play,
  Plug,
  Plus,
  PlusCircle,
  Puzzle,
  Pyramid,
  Radar,
  Radio,
  RefreshCcw,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Router,
  Rss,
  Satellite,
  Save,
  Scale,
  ScanLine,
  ScanSearch,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShieldX,
  Ship,
  Skull,
  Sliders,
  Smartphone,
  Snowflake,
  SortAsc,
  SortDesc,
  Sparkles,
  Split,
  Square,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Target,
  Telescope,
  Terminal,
  TestTube2,
  ThumbsDown,
  ThumbsUp,
  Timer,
  ToggleLeft,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Type,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCircle,
  Users,
  Wallet,
  Wand2,
  Waves,
  Webhook,
  Wifi,
  WifiOff,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
  Handshake,
  BadgeCheck,
  GitCommitHorizontal,
} from 'lucide-react'

export type { LucideIcon }

/**
 * Map of all icon names to their LucideIcon components.
 * Used for dynamic icon resolution (e.g., `iconRegistry['Server']`).
 */
export const iconRegistry: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Anchor,
  Apple,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpFromLine,
  ArrowUpRight,
  Award,
  Banana,
  BarChart2,
  BarChart3,
  Bell,
  BellOff,
  Bird,
  Bomb,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Calendar,
  CalendarDays,
  Car,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleDot,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudFog,
  CloudRain,
  CloudSnow,
  Club,
  Code,
  Code2,
  Cog,
  Coins,
  Columns,
  Compass,
  Container,
  Copy,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Diff,
  DollarSign,
  Download,
  Edit,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck,
  FileCode,
  FileDiff,
  FileJson,
  FileKey,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderGit,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Footprints,
  FormInput,
  Gamepad2,
  Gauge,
  Ghost,
  Gift,
  GitBranch,
  GitCompare,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  Grid2X2,
  Grid3X3,
  GripVertical,
  Hammer,
  HardDrive,
  Heart,
  HeartPulse,
  HelpCircle,
  Hexagon,
  History,
  Hourglass,
  Image,
  ImageOff,
  Info,
  Key,
  KeyRound,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Lightbulb,
  Link,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  MemoryStick,
  Menu,
  MessageSquare,
  MessageSquareText,
  Microscope,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Navigation,
  Network,
  Newspaper,
  Package,
  Palette,
  Pause,
  Pencil,
  Percent,
  PieChart,
  Play,
  Plug,
  Plus,
  PlusCircle,
  Puzzle,
  Pyramid,
  Radar,
  Radio,
  RefreshCcw,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Router,
  Rss,
  Satellite,
  Save,
  Scale,
  ScanLine,
  ScanSearch,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShieldX,
  Ship,
  Skull,
  Sliders,
  Smartphone,
  Snowflake,
  SortAsc,
  SortDesc,
  Sparkles,
  Split,
  Square,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Target,
  Telescope,
  Terminal,
  TestTube2,
  ThumbsDown,
  ThumbsUp,
  Timer,
  ToggleLeft,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Type,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCircle,
  Users,
  Wallet,
  Wand2,
  Waves,
  Webhook,
  Wifi,
  WifiOff,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
  Handshake,
  BadgeCheck,
  GitCommitHorizontal,
}

/**
 * Kubernetes helm wheel icon — used for Multi-Tenancy dashboard sidebar.
 * Simplified 7-spoke wheel matching the K8s logo.
 * Uses createElement since this is a .ts file (no JSX).
 */
import { createElement, type SVGProps } from 'react'

const KubernetesWheel: LucideIcon = Object.assign(
  (props: SVGProps<SVGSVGElement> & { size?: number | string }) => {
    const { size: s = 24, className, ...rest } = props
    return createElement('svg', {
      viewBox: '0 0 24 24', width: s, height: s, className,
      fill: 'none', stroke: 'currentColor', strokeWidth: '1.5',
      strokeLinecap: 'round', strokeLinejoin: 'round', ...rest,
    },
      createElement('circle', { cx: 12, cy: 12, r: 10 }),
      createElement('circle', { cx: 12, cy: 12, r: 3 }),
      createElement('line', { x1: 12, y1: 2, x2: 12, y2: 9 }),
      createElement('line', { x1: 12, y1: 15, x2: 12, y2: 22 }),
      createElement('line', { x1: 2.93, y1: 7.5, x2: 9.46, y2: 10.5 }),
      createElement('line', { x1: 14.54, y1: 13.5, x2: 21.07, y2: 16.5 }),
      createElement('line', { x1: 2.93, y1: 16.5, x2: 9.46, y2: 13.5 }),
      createElement('line', { x1: 14.54, y1: 10.5, x2: 21.07, y2: 7.5 }),
    )
  },
  { displayName: 'KubernetesWheel' },
) as unknown as LucideIcon

/**
 * Brand icons — removed from lucide-react v1.0 (brand icons are no longer bundled).
 * Custom SVG implementations that match the lucide style (24x24, stroke-based).
 */

/** GitHub octocat logo (stroke-based approximation) */
export const Github: LucideIcon = Object.assign(
  (props: SVGProps<SVGSVGElement> & { size?: number | string }) => {
    const { size: s = 24, className, ...rest } = props
    return createElement('svg', {
      viewBox: '0 0 24 24', width: s, height: s, className,
      fill: 'none', stroke: 'currentColor', strokeWidth: '2',
      strokeLinecap: 'round', strokeLinejoin: 'round', ...rest,
    },
      createElement('path', {
        d: 'M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4',
      }),
      createElement('path', { d: 'M9 18c-4.51 2-5-2-7-2' }),
    )
  },
  { displayName: 'Github' },
) as unknown as LucideIcon

/** LinkedIn logo (stroke-based approximation) */
export const Linkedin: LucideIcon = Object.assign(
  (props: SVGProps<SVGSVGElement> & { size?: number | string }) => {
    const { size: s = 24, className, ...rest } = props
    return createElement('svg', {
      viewBox: '0 0 24 24', width: s, height: s, className,
      fill: 'none', stroke: 'currentColor', strokeWidth: '2',
      strokeLinecap: 'round', strokeLinejoin: 'round', ...rest,
    },
      createElement('path', {
        d: 'M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z',
      }),
      createElement('rect', { width: '4', height: '12', x: '2', y: '9' }),
      createElement('circle', { cx: '4', cy: '4', r: '2' }),
    )
  },
  { displayName: 'Linkedin' },
) as unknown as LucideIcon

/** Slack logo (stroke-based approximation) */
export const Slack: LucideIcon = Object.assign(
  (props: SVGProps<SVGSVGElement> & { size?: number | string }) => {
    const { size: s = 24, className, ...rest } = props
    return createElement('svg', {
      viewBox: '0 0 24 24', width: s, height: s, className,
      fill: 'none', stroke: 'currentColor', strokeWidth: '2',
      strokeLinecap: 'round', strokeLinejoin: 'round', ...rest,
    },
      createElement('rect', { width: '3', height: '8', x: '13', y: '2', rx: '1.5' }),
      createElement('path', { d: 'M19 8.5V10h1.5A1.5 1.5 0 1 0 19 8.5' }),
      createElement('rect', { width: '3', height: '8', x: '8', y: '14', rx: '1.5' }),
      createElement('path', { d: 'M5 15.5V14H3.5A1.5 1.5 0 1 0 5 15.5' }),
      createElement('rect', { width: '8', height: '3', x: '14', y: '13', rx: '1.5' }),
      createElement('path', { d: 'M15.5 19H14v1.5a1.5 1.5 0 1 0 1.5-1.5' }),
      createElement('rect', { width: '8', height: '3', x: '2', y: '8', rx: '1.5' }),
      createElement('path', { d: 'M8.5 5H10V3.5A1.5 1.5 0 1 0 8.5 5' }),
    )
  },
  { displayName: 'Slack' },
) as unknown as LucideIcon

// Add custom icons to registry
iconRegistry.KubernetesWheel = KubernetesWheel
iconRegistry.Github = Github
iconRegistry.Linkedin = Linkedin
iconRegistry.Slack = Slack

/**
 * Resolve an icon component by name, falling back to HelpCircle if not found.
 */
export function getIcon(name: string): LucideIcon {
  return iconRegistry[name] || HelpCircle
}
