name: Add Help Wanted Label

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  label:
    uses: kubestellar/infra/.github/workflows/reusable-add-help-wanted.yml@5c7fdcdde035388fa2df43d860d2372c2dd3e3ed  # main
    timeout-minutes: 5
    secrets: inherit
