name: Assignment Helper

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assignment-helper:
    uses: kubestellar/infra/.github/workflows/reusable-assignment-helper.yml@5c7fdcdde035388fa2df43d860d2372c2dd3e3ed  # main
    timeout-minutes: 5
