name: Feedback Wanted

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  feedback:
    uses: kubestellar/infra/.github/workflows/reusable-feedback.yml@5c7fdcdde035388fa2df43d860d2372c2dd3e3ed  # main
    timeout-minutes: 5
    secrets: inherit
