name: Greetings

on:
  pull_request_target:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  greet:
    if: github.event_name == 'issues' || github.event.pull_request.head.repo.full_name == github.repository
    uses: kubestellar/infra/.github/workflows/reusable-greetings.yml@5c7fdcdde035388fa2df43d860d2372c2dd3e3ed  # main
    timeout-minutes: 5
